# Generated by Django 4.1.2 on 2022-11-06 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbAgendamentosmes',
            fields=[
                ('agm_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('agm_data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TbBairros',
            fields=[
                ('bai_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('bai_bairro', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TbEstados',
            fields=[
                ('est_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('est_estado', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TbLocal',
            fields=[
                ('loc_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('loc_logradouro', models.CharField(max_length=150)),
                ('loc_numero', models.IntegerField()),
                ('loc_nomeunidadedeservico', models.CharField(max_length=150)),
                ('loc_bai_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agendamento.tbbairros')),
            ],
        ),
        migrations.CreateModel(
            name='TbHorarios',
            fields=[
                ('hor_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('hor_horariosaida', models.TimeField(default='')),
                ('hor_horarioentrada', models.TimeField(default='')),
                ('hor_agm_codigo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Agendamento.tbagendamentosmes')),
                ('hor_loc_codigo', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Agendamento.tblocal')),
            ],
        ),
        migrations.CreateModel(
            name='TbCidades',
            fields=[
                ('cid_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('cid_cidade', models.CharField(max_length=50, unique=True)),
                ('cid_est_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agendamento.tbestados')),
            ],
        ),
        migrations.AddField(
            model_name='tbbairros',
            name='bai_cid_codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agendamento.tbcidades'),
        ),
    ]
